name: Checks
on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

jobs:
  Coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - run: npm install
      - run: npx hardhat coverage

      - name: Coveralls
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Code Coverage Report Comment
        if: ${{ github.event.issue.pull_request }}
        uses: romeovs/lcov-reporter-action@v0.2.16
        with:
          lcov-file: ./coverage/lcov.info
